# Generated by Django 4.0.5 on 2022-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='Zagalovoc')),
                ('author', models.CharField(default='Unknown', max_length=50, verbose_name='Author')),
                ('content', models.TextField(max_length=3000, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Statya',
                'verbose_name_plural': 'Statii',
                'db_table': 'articles',
            },
        ),
    ]
