# Generated by Django 4.0.5 on 2022-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'Processing'), ('done', 'Completed')], default='new', max_length=50, verbose_name='Status'),
        ),
    ]
