# Generated by Django 4.0.5 on 2022-07-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20220712_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
